server:
  port: 8080
spring:
  data:
    mongodb:
      database: yfy
      #mongodb集群相关配置
      ip-and-ports: 192.168.11.27:20000,192.168.11.28:20000,192.168.11.44:20000
      #mongodb用户账号密码相关配置
      dbname: yfy
      username: mongouser
      pwd: infunmongo
      hostport: mongo.infuneye.com:27017
      connectionsPerHost: 8
      threadsAllowedToBlockForConnectionMultiplier: 4
      #连接超时时间
      connectTimeout: 1000
      #等待时间
      maxWaitTime: 1500
      autoConnectRetry: true
      socketKeepAlive: true
      #Socket超时时间
      socketTimeout: 1500
      slaveOk: true