server:
  #服务端口号
  port: 8080
spring:
  #配置redis
  redis:
    #redis集群
    cluster:
      nodes: 172.18.190.114:6001,172.18.190.114:6002,172.18.190.115:6001,172.18.190.115:6002,172.18.190.116:6001,172.18.190.116:6002
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 300
      # 连接池中的最小空闲连接
      min-idle: 1
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      test-on-borrow: true
      test-while-idle: true
